language: python
python:
  - 2.7
  - 3.4
  - 3.5
services: mongodb
env:
  - PYMONGO_VERSION='>=2.6,<2.9'
  - PYMONGO_VERSION='>=3.5,<3.6'
  - PYMONGO_VERSION=''  # Allow latest
install:
  - pip install --use-mirrors "pymongo $PYMONGO_VERSION"
  - pip install --use-mirrors .
  - pip install --use-mirrors coveralls coverage
script: >
  if [[ $TRAVIS_PYTHON_VERSION == 3* ]];
  then coverage run --source=humbledb setup.py test; true;
  else coverage run --source=humbledb setup.py test; fi

after_success: coveralls
