language: python
python:
  - 2.7
  - 3.5
  - 3.6
services: mongodb
env:
  - PYMONGO_VERSION='<3'
  - PYMONGO_VERSION='<3.6'
  - PYMONGO_VERSION=''  # Allow latest
install:
  - pip install "pymongo $PYMONGO_VERSION"
  - pip install .
  - pip install coveralls coverage
script: >
  coverage run --source=humbledb setup.py test

after_success: coveralls
