language: python
python:
  - 2.7
  - 3.5
  - 3.6
services: mongodb
env:
  - PYMONGO_VERSION='<3'
  - PYMONGO_VERSION='<3.6'
  - PYMONGO_VERSION=''  # Allow latest
install:
  - pip install "pymongo $PYMONGO_VERSION"
  - pip install .
  - pip install coveralls coverage
script: >
  if [[ $TRAVIS_PYTHON_VERSION == 3* ]];
  then coverage run --source=humbledb setup.py test; true;
  else coverage run --source=humbledb setup.py test; fi

after_success: coveralls
